### ISSUE TITLE
Suggestion: Use headless UI library

### ISSUE THREAD

**Issue by StyleShit** [ykadosh/notify#7]
Hey!

Saw this on codepen yesterday (and somehow today on Twitter), looks great!
I went over the code. Maybe you can use something like radix ui / headless ui in order to simplify your logic and get tons of features for free (a11y, popper, portals, touch gestures, etc.).

https://www.radix-ui.com/docs/primitives/components/toast

Let's talk if you need some help. I'll be glad to send some PRs :)

**Comment by ykadosh** [comment]
Hey! Thanks for the feedback 👍

I'm a big believer in headless UI (I even built a whole library based on this concept - [webrix](https://webrix.amdocs.com).
But I wanted to keep this library slim and independent.

**Comment by StyleShit** [comment]
Sure :)
